### ISSUE TITLE
Basic data presentation

### ISSUE THREAD

**Issue by sh1nj1** [codeforseoul/how-much-shoveling#2]
``` javascript
{
"total": 1000
"name": Citi Hall
"latitude": 35.342134
"logitude": 66.234234
"startedAt": 1999-01-01
"finishedAt": null
}
```

위와 같은 데이터가 여러개 정의 되어 있다 고가정하고
구글 지도 위에 total 값에 따라 서로 다른 크기의 원을 그리고 name, startedAt, finishedAt, total 정보를 표시한다.
If there is array data that looks like above data structure, represent it as circle on the google map and show its name, startedAt and finishedAt.

**Comment by dkmin** [comment]
I'm on it. let me try ;)

**Comment by sh1nj1** [comment]
@dkmin :+1: please commit source code and some description.

**Comment by sh1nj1** [comment]
resource
web-app

이렇게 큰 카테고리로 폴더를 만들어야겠습니다.
